sudo: required

services:
  - docker

env:
  - docker_img_a=gsauthof/fedora-cxx-devel:23 docker_img_b=gsauthof/fedora-cxx-runtime:23 CMAKE_BUILD_TYPE=SanitizeO
  - docker_img_a=gsauthof/fedora-cxx-devel:23 docker_img_b=gsauthof/fedora-cxx-runtime:23 CMAKE_BUILD_TYPE=Coverage
  - docker_img_a=gsauthof/fedora-mingw64-devel:23 docker_img_b=gsauthof/fedora-mingw64-runtime:23 run_tag="_mingw" CMAKE_BUILD_TYPE=Release

# default is ruby, we set python in case we need to do some
# advanced scripting in our setup of the C++ tests
language: python
python: 3.5

before_install:
  - ./ci/travis/before_install.sh

install:
  - ./ci/travis/install.sh

before_script:
  - ./ci/travis/before_script.sh

script:
  - ./ci/travis/script.sh

after_success:
  - ./ci/travis/after_success.sh

after_script:
  - ./ci/travis/after_script.sh

#after_failure:
#
before_deploy:
  - ./ci/travis/before_deploy.sh

deploy:
  provider: bintray
  on:
    condition: $run_tag = _mingw
  file: "$HOME/deploy/bintray_w64.json"
  user: "gsauthof"
  key:
    secure: "BRURI1Qa9Cm0LJdYHCbS9j7Sme8218hghp13mClCUz5ECr6mOe8lQiqNJhOC3ifXGiIhW4G6QdpAqyYlfXqAxloxcnpJG+uvBx9kK4J4Fexzbf+XcSZlrOuP+z4ZxOiXcRf0CysqyQ7h8/h9knpsv2j5nDA+Ug3yI0319VEKToixpTKLpQUQA6HfK+BTD4RHW2+TmRi2KW5VbIA0pbvH/nbHkf9bCrDINAw4RgnzEX8CEa3k50Jky/jlw1AWIH7k0gzTlmkW1Y3SPzUNczpEqEYg4kxO3bIUiyTx8K2XqKIRT44hm81P/WfH+tzJ6WNEyP2KjSJpYYbxRQ5d2IplvE3jJ5PdCTUa+RWTchHJpn5YRQalYXw/PHTVo7CIFfHdxEQGNNWinGZg3MHNH55t1KakahlnFHsI5vBmsa/51KsOomQymYK92jfA1U3VtOMEGs/DMU70WHUv/xxmEwFnde+L3rfFkgoPZElIMo16mpfbAhmM129rnRBiFyIk5uMT2pJrmWfrZRT+KskTip5ccF8NZH7zVNNChvM/JU182yg3E5gRijiW2WVJ5Q1T2cFJgug33weh7aXt3QLGYZ/890DarBPF/0xYxZNCjGWKAGNYogooGnVp0nebyb8cmPcpSjhsAaBM9G/ES69uHqMuEcsTQE/jp1F3YoXRbx1osag="

#after_deply:

#after_script:
